"""add_randomization_settings

Revision ID: 1c45b4f3243e
Revises: 8f08e63bf7a6
Create Date: 2025-12-31 14:39:28.552557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c45b4f3243e'
down_revision = '8f08e63bf7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('randomize_question_order', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('randomize_answer_options', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_anti_cheating', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    
    # Set default values for existing rows
    op.execute("UPDATE quiz_settings SET randomize_question_order=0 WHERE randomize_question_order IS NULL")
    op.execute("UPDATE quiz_settings SET randomize_answer_options=0 WHERE randomize_answer_options IS NULL")
    op.execute("UPDATE quiz_settings SET enable_anti_cheating=0 WHERE enable_anti_cheating IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_settings', schema=None) as batch_op:
        batch_op.drop_column('enable_anti_cheating')
        batch_op.drop_column('randomize_answer_options')
        batch_op.drop_column('randomize_question_order')

    # ### end Alembic commands ###
